name: Check commit messages
on: [push, pull_request]
jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install GitHub::Actions
        run: sudo cpan GitHub::Actions
      - name: Ref issue present in a commit
        shell: perl {0}
        if: ${{! contains(github.event.head_commit.message, '#') }}
        run: |
          use GitHub::Actions;
          set_failed( "Last commit should refer to an issue" );
