name: Check commit messages
on: [push, pull_request]
jobs:
  hello-perl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Ref issue present in a commit
        shell: perl {0}
        run: |
          use Git;
          die "::error::Last commit should refer to an issue"
              if ( Git->repository->command("log", "--oneline", "-1") !~ /\#/ );
