name: Hello Perl
on: [push, pull_request]
jobs:
  hello-perl:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Perl
        shell: perl {0}
        env:
          ACTION: ${{ github.action }}
        run: |
          use Perl::OSType qw(os_type);
          use Time::HiRes qw(tv_interval);
          my $t0 = [gettimeofday];
          print "Hey $ENV{'GITHUB_ACTOR'} from $ENV{'GITHUB_ACTION'} running on ", os_type(), " for ", tv_interval ( $t0 );
